# Generated by Django 4.1.5 on 2023-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "Mon"),
                            ("tue", "Tue"),
                            ("wed", "Wed"),
                            ("thu", "Thu"),
                            ("fri", "Fri"),
                            ("sat", "Sat"),
                            ("sun", "Sun"),
                        ],
                        max_length=60,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
