# Generated by Django 4.1.5 on 2023-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0001_initial"),
        ("games", "0004_alter_game_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(related_name="genres", to="genres.genre"),
        ),
    ]
